#!/bin/sh

DEPS=(
	Common.hpp
	Common.cpp
	Agent.hpp
	Agent.cpp
	Options.hpp
	Options.cpp
	Map.hpp
	Map.cpp
	Evolution.hpp
	Evolution.cpp
	main.cpp
)

output="CGSolver"
cat "${DEPS[@]}" > $output.cpp
sed -i -e '/HPP/d' -e '/include "/d' $output.cpp
g++ $output.cpp -o $output -std=c++17 -Wall -Wextra -Wreorder -Ofast -O3 -flto -march=native -s
rm $output
clipcp $output.cpp
